package de.tud.kitchen.steamer;

/**
 * EventCallback
 *
 * This interface handles events that are generated by the Steamer.
 *
 * @author Andrew.Tokmakoff@philips.com
 * @author niklas@tk.informatik.tu-darmstadt.de
 *
 */

public interface EventCallback
{
	public void descale();
	public void refill();
	public void steamingOn();
	public void steamingOff();
	
}
