// This file was generated by mcc 1.0.3. DO NOT EDIT THIS FILE!
// classname: org.mundo.blender.IBlender

package org.mundo.blender;

import org.mundo.rt.ActiveArray;
import org.mundo.rt.ActiveMap;

//@mcRemote(className="org.mundo.blender.IBlender")
public interface IBlender
{
  public boolean pushButton(int but);
  public boolean pushButton(int button, int time);
  public boolean lightOn(boolean toggle);
  public static final int PULSE=0x04;
  public static final int ERROR_MSG=-1;
  public static final int SMOOTHIE=0x01;
  public static final int ICE=0x02;
}

