// This file was generated by mcc 1.0.3. DO NOT EDIT THIS FILE!
// classname: org.mundo.blender.IBlenderEvent

package org.mundo.blender;

import org.mundo.rt.ActiveArray;
import org.mundo.rt.ActiveMap;

//@mcRemote(className="org.mundo.blender.IBlenderEvent")
public interface IBlenderEvent
{
  public void buttonPushed(int but);
  public void buttonReleased(int button);
  public static final int PULSE=0x04;
  public static final int DIAL_ON=0x08;
  public static final int SMOOTHIE=0x01;
  public static final int DIAL_RANGE=0x10;
  public static final int ICE=0x02;
}

